name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: yourGitHubUsername
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push the generated files
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Generated Contribution Snake"
          add: "dist/*.svg"
